server:
  port: 1002

#在application.properties/或者application.yml文件中没有添加数据库配置信息.
spring:
  datasource:
    url: jdbc:mysql://123.57.235.2:3306/weixin?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: dongzhizhuo
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    allow-bean-definition-overriding: true

mybatis-plus:
  global-config:
    refresh: true
  # mybatis-plus 日志打印
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#=========微信公众号开发基本配置============
# 微信公众号 id
#wx_appid: wxf9a9157f56a82f1f
#微信公众号的appsecret
#wx_appsecret: 812ed431acc8a49ed6f92aac2b544987
#微信公众号的token
# wx_token: xxx
#微信公众号的消息加解密密钥aeskey

# wx_aeskey: WoDWc9c9jseK4gYzOcZChVaGDkcLTgmoS3O2F7KZtWV

WeChat:
  AppID: wxf9a9157f56a82f1f
  AppSecret: 812ed431acc8a49ed6f92aac2b544987
  TemplateID: JsMASbrsevRTq4UClpgEvVXwzRSJvNlUep75TOZ-q2Q





